#For more information see:https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python
name: CI - BookClubQA

on:
  pull_request:
    branches: [ main ]  # Запускать workflow при пуше в ветку main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Настройки Python
      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"  # Установка нужной версии Python

        # Установка зависимостей из requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Обновление pip
          pip install -r requirements.txt  

      - name: Verify installed packages
        run: pip freeze

      # Установка необходимых браузеров Playwright Chrome.
      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium
          
     #Установка линтера Ruff    
      - name: Install the code linting and formatting tool Ruff
        run: pip install ruff

      # Проверка форматирования кода Ruff
      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py312

      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py312
        continue-on-error: true # Не останавливает CI, если есть проблемы с форматированием(сомнительно)

      # Запуск всех тестов(стоп на 1 упавшем тесте, мин инф о тестах)
      - name: Run tests
        run: |
          pytest -s --maxfail=1 --disable-warnings -q 
        env:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1

      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v2
      #   if: always()
      #   with:
      #     files: |
      #       test-results/**/*.xml
          

